### ISSUE TITLE
Why does this require transpilation?

### ISSUE THREAD

**Issue by davidporter-id-au** [seek-oss/seek-style-guide#115]
As in, is there a technical reason why it couldn't bundle its assets in a `/dist` folder, thus preventing the need to use babel on `node_modules` in a consuming project?

**Comment by markdalgleish** [comment]
If this was just a JavaScript project, we'd definitely compile before publishing, but since our project uses multiple asset types (CSS, images, fonts) we need to leverage webpack. There currently isn't a standard way of publishing webpack packages, so for now we've opted for the current approach.

The only way out of this I can see right now is to switch to CSS-in-JS for everything and move away from webpack, but that's a much larger discussion.

Closing for now, but feel free to catch up with me offline if you want to talk this through further.
