### ISSUE TITLE
Demo page isn't updating props but rerendering a full new component

### ISSUE THREAD

**Issue by dborysiewicz** [seek-oss/seek-style-guide#276]
Issues like this https://github.com/seek-oss/seek-style-guide/pull/275 are missed as it works in the demo however when implemented into a real application it dosen't work. This would also be a source of why transitions are not seen.

**Comment by markdalgleish** [comment]
Had a look into this, and realised it's because we're generating a new component inside the render function for `<Demo>`, which means that the component being demoed is actually being destroyed and recreated on every render: https://github.com/seek-oss/seek-style-guide/blob/96c18fa3b8906fdc5fb709dfd4d39933bd6e758a/docs/src/components/Demo/Demo.js#L130
