### ISSUE TITLE
Module parse failed: Unexpected token in Button.js

### ISSUE THREAD

**Issue by Goaty89** [seek-oss/seek-style-guide#389]
Try to install this in a whole new createReactApp. It does not work expected. What is the Button.js expected module need? 

`/node_modules/seek-style-guide/react/Button/Button.js
Module parse failed: Unexpected token (10:21)
You may need an appropriate loader to handle this file type.
| 
| export default class Button extends Component {
|   static displayName = 'Button';
| 
|   static propTypes = {`

**Comment by markdalgleish** [comment]
This package doesn't work with create-react-app because you need to modify your webpack config to support it, and create-react-app abstracts webpack away from you. You can eject and integrate manually using [seek-style-guide-webpack](https://github.com/seek-oss/seek-style-guide-webpack), or you could look at using [sku](https://github.com/seek-oss/sku) instead.

**Comment by markdalgleish** [comment]
What brings you here, by the way? What are you trying to build? 😄
